Include cross validation
wgrisa/express-yup-middleware pull request #2
Opened 2020-06-24 22:36 UTC by wellgrisa

2020-06-25 19:24 UTC, wgrisa requested changes

2020-06-25 19:24 UTC, wgrisa commented on README.md
> +The middleware puts the req in the context. Therefore it's possible to use the other properties to validate. Remember that to make use of `this` it's necessary to use a function (not an arrow one).
You can cross-validate properties of your payload using a custom Yup test and accessing them by calling `this.options.context`.

2020-06-25 19:24 UTC, wgrisa commented on README.md
> +## Validating using cross properties (body, params or query)
Cross-validation using any properties from your payload

2020-06-25 19:24 UTC, wgrisa commented on README.md
> +          message: 'Check if your number correspond with the type given',
Check if your number corresponds with the given type

2020-06-25 19:24 UTC, wgrisa commented on README.md
> +            if (type === 'even') return mod === 0
Add the brackets for these if statements.

2020-06-25 19:24 UTC, wgrisa commented on test/yup-middleware.spec.ts
> +    it('returns a bad request error using a param value within a body validation', async () => {
returns a bad request error when the number sent in the payload does not match the type param

2020-06-25 19:24 UTC, wgrisa commented on test/yup-middleware.spec.ts
> +              message: 'Check if your number correspond with the type given',
Check if your number corresponds with the given type

2020-06-25 19:24 UTC, wgrisa commented on test/yup-middleware.spec.ts
> +              propertyPath: 'numberToValidate',
typeMismatch

2020-06-25 19:24 UTC, wgrisa commented on test/yup-middleware.spec.ts
> +                message: 'Check if your number correspond with the type given',
Check if your number corresponds with the given type

2020-06-29 23:19 UTC, wellgrisa commented on test/yup-middleware.spec.ts
> +              propertyPath: 'numberToValidate',
Did not understand :(

2020-07-01 21:07 UTC, wgrisa requested changes

2020-07-01 21:07 UTC, wgrisa commented on src/schema-validator.ts
> +          req: payload,
use payload instead of req as it can be anything, not necessarily an express request object

2020-07-02 00:22 UTC, wgrisa approved these changes

2020-07-02 00:22 UTC, merged